### ISSUE TITLE
почему бы не сбилдить готовый exe?

### ISSUE THREAD

**Issue by AnimeLore** [PulseSync-LLC/YMusic-DRPC#41]
может чего не понимаю, но почему бы не собрать приложение в exe? и закинуть его в релизы, чтобы не приходилось постоянно кучу зависимостей качать на уровне системы

**Comment by riivx** [comment]
так это ещё и по логике максимально просто, банальный `npm run make` должен работать, сейчас проверю даже

**Comment by Maks1mio** [comment]
да только сейчас работа идёт над этой веткой https://github.com/PulseSync-Official/YMusic-DRPC/tree/patcher-ts и парочкой других: https://github.com/PulseSync-Official/PulseSync-backend, https://github.com/PulseSync-Official/PulseSync-website

как только всё будет налажено то выгрузим готовый exe с авто обновлениями

**Comment by Maks1mio** [comment]
![image](https://github.com/PulseSync-Official/YMusic-DRPC/assets/44835662/58406859-9dac-4538-8820-9a0c5a0c63e4)

**Comment by Maks1mio** [comment]
нужно будет исправить некоторые баги ибо это работает в паре с react

**Comment by riivx** [comment]
как я понимаю, нас, судя по иконкам, ждёт не только rpc, но ещё и темы? или же это для патчера только

**Comment by foreA-adoxid** [comment]
темы для яндекс музыки.

**Comment by foreA-adoxid** [comment]
в дискорд сервере есть семплы
![image](https://github.com/PulseSync-Official/YMusic-DRPC/assets/72875762/8867293b-52d4-4098-bd83-955f6e059c2b)
