### ISSUE TITLE
RPC не подключается к инету, или что-то подобное

### ISSUE THREAD

**Issue by Mihail20227** [PulseSync-LLC/YMusic-DRPC#60]
![Снимок экрана (727)](https://github.com/user-attachments/assets/54bc4b1f-e528-4eb1-85d1-12bccd68c7a3)

**Comment by Mihail20227** [comment]
> Здравствуйте, ошибка подключения к Дискорду, он запущен?
да

**Comment by Mihail20227** [comment]
> Здравствуйте, ошибка подключения к Дискорду, он запущен?

да

**Comment by Mihail20227** [comment]
> Здравствуйте, ошибка подключения к Дискорду, он запущен?

на скрине не запущен, но с запущенным такая же хрень

**Comment by Mihail20227** [comment]
![image](https://github.com/user-attachments/assets/2177043b-60e4-4407-bcd2-a2604b40e877)

**Comment by Antonzlo** [comment]
Проверьте что включен rpc в настройках, и что Дискорд не запущен от имени администратора. Дальше попробуйте перезагрузить ПК
